<?php
require('fpdf.php');
ob_start();
header("Content-Encoding: None", true);

$con=mysqli_connect("localhost:3307", "root", "", "pdfdemo");

$id=$_GET['id'];

$rc=mysqli_query($con,"select * from receipt where rno='$id'");
$row=mysqli_fetch_array($rc);

include("digtoword.php");
$word = ucwords(numberTowords($row[6]))." Only";

	
$pdf = new FPDF('P','mm','A4');
//add new page
$pdf->AddPage();
$pdf->Image('title.jpg', 10, 12, 55, 12);
$pdf->Image('logo.png', 115, 11, 22, 22);
$pdf->Image('sign.jpg', 154, 75, 40, 17);
//set font to arial, bold, 14pt

//Cell(width , height , text , border , end line , [align] )
$pdf->SetFont('Arial','',8);
$pdf->Cell(130 ,3,'Managed by Madhav Education & Charitable Trust',0,0);
$pdf->Cell(59 ,3,'',0,1);//end of line
$pdf->SetFont('Arial','B',14);
$pdf->Cell(130 ,5,'',0,0);
$pdf->Cell(59 ,5,'RECEIPT',0,1);//end of line

//set font to arial, regular, 12pt
$pdf->SetFont('Arial','B',12);

$pdf->Cell(130 ,5,'',0,0);
$pdf->Cell(59 ,5,'',0,1);//end of line
$pdf->SetFont('Arial','',10);
$pdf->Cell(130 ,5,'Porbandar, Gujarat',0,0);
$pdf->Cell(25 ,5,'Date',0,0);
$pdf->Cell(34 ,5,$row[1],0,1);//end of line

$pdf->Cell(130 ,5,'Contact: 9033392721',0,0);
$pdf->Cell(25 ,5,'Receipt #',0,0);
$pdf->Cell(34 ,5,$row[0],0,1);//end of line

$pdf->Cell(130 ,5,'Email: miwtindia@gmail.com',0,0);
$pdf->Cell(25 ,5,'',0,0);
$pdf->Cell(34 ,5,'',0,1);//end of line

//make a dummy empty cell as a vertical spacer
$pdf->Cell(189 ,10,'',0,1);//end of line

//billing address
$pdf->SetFont('Arial','',11);
$pdf->Cell(50 ,5,'Received with thanks from',0,0);
$pdf->SetFont('Arial','B',11);
$pdf->Cell(139 ,5,$row[3],1,1);//end of line

$pdf->Cell(189 ,3,'',0,1);//end of line

$pdf->SetFont('Arial','',11);
$pdf->Cell(36 ,5,'Rupees (in words)',0,0);
$pdf->Cell(153 ,5,$word,1,1);//end of line

$pdf->Cell(189 ,3,'',0,1);//end of line

$pdf->Cell(7 ,5,'by ',0,0);
$pdf->Cell(42 ,5,$row[7],1,0);
$pdf->Cell(21 ,5,' of Course ',0,0);
$pdf->Cell(119 ,5,$row[5],1,1);//end of line

//make a dummy empty cell as a vertical spacer
$pdf->Cell(189 ,10,'',0,1);//end of line

//invoice contents
$pdf->SetFont('Arial','B',12);

$pdf->Cell(9 ,5,'Rs.',0,0);
$pdf->Cell(30 ,5,$row[6],1,0);
$pdf->Cell(110 ,5,'',0,0);
$pdf->SetFont('Arial','',11);
$pdf->Cell(40 ,5,'Autho. Signatory',0,1);
$pdf->Cell(189 ,10,'',0,1);//end of line
//invoice contents

$pdf->SetFont('Arial','B',9);
$pdf->Cell(9 ,5,'e-Receipt generated by Online Student Portal <student.miwtindia.com>',0,0);

ob_end_clean();
$pdf->Output();
?>